### ISSUE TITLE
Infinite Rotation

### ISSUE THREAD

**Issue by oschade** [pryomoax/rocket-nuimo-node#10]
I don't know if this is the default behavior of the nuimo: Is it possible to get infinite rotation delta values? Right now it, no more rotation events triggered after the nuimo reach the rotationMaximum / rotationMinimum.

**Comment by happycodelucky** [comment]
This is something I could add, I would need to think about the design. The code does clamp the rotation. Honestly I never liked the implementation I added for these reasons.

**Comment by happycodelucky** [comment]
For the interim you can set min to -1 and max to 1, and on each rotation event reset the rotation value. This ensures you would get positive and negative rotations.

**Comment by happycodelucky** [comment]
Alright, I've implemented new behavior quickly. As not to break backwards compatibility I've introduced a new property [`rotationMode`](https://github.com/happycodelucky/rocket-nuimo-node/blob/main/src/model/nuimo-control-device.ts#L158).

Check out the example https://github.com/happycodelucky/rocket-nuimo-node/blob/main/examples/05-rotate-events/example-rotate-events.ts#L15. You can now set the mode to `Continuous`, and remove the call to `setRotationRange` as this will error out when in continuous mode.

Note, as rotation cannot really be determined it always returns `0` in continuous mode. You have to rely on the rotation delta (relative to a single rotation).
