### ISSUE TITLE
Missing package-lock.json

### ISSUE THREAD

**Issue by riker09** [pryomoax/rocket-nuimo-node#11]
Is there any particular reason, why there is no `package-lock.json` committed to this repo? I believe it is good practise to provider other developers with that file. They will get the same packages you installed during development, while later versions occacionally break stuff.

**Comment by happycodelucky** [comment]
Ah, I use `yarn` so there’s a `yarn.lock`. `npm` 7 now supports yarn’s lock files

**Comment by happycodelucky** [comment]
Any reason you need `package-lock.JSON` in this repo? The published package on npmjs.org is always built and publish with yarn

**Comment by riker09** [comment]
No. I was just curious. Guess I should use this as an excuse to update to npm v7 then. :)
