### ISSUE TITLE
Anyone implementing the code?

### ISSUE THREAD

**Issue by Trisk3lion** [pryomoax/rocket-nuimo-node#2]
Hello, this looks like a awesome work!
I haven nuimo lying in the drawer, collecting dust, which I would love to use. Do you know if any application are implementing your code?

**Comment by thedriveman** [comment]
@pryomoax thank you so much for building this awesome API. I'm going to use it to control my Mac's volume.

**Comment by happycodelucky** [comment]
Glad to help!

Let me know if you find any bugs. The package has been used in long term
use prototypes. You’ll need to author your own disconnect and reconnect
handing.

Paul

**Comment by happycodelucky** [comment]
No action here
