### ISSUE TITLE
Controller sleep mode / rotate events are not dispatched after 5 min of inactivity

### ISSUE THREAD

**Issue by thedriveman** [pryomoax/rocket-nuimo-node#4]
I'm building an app that listens to rotate events, and I've noticed that after about 5 minutes of inactivity (i.e., not touching the controller), rotate events stop getting dispatched . However, once I press the controller surface, a select event is getting dispatched, after which rotate events start dispatching again. It does look like the Bluetooth connection remains connected during the entire time, as no disconnected event is dispatched. 

Does the controller hardware go to "light" sleep after 5 minutes, where only a select event wakes it up?

**Comment by happycodelucky** [comment]
Yes, although I’m not sure of the exact timing. It’s been a while, but you
can try sending heart beat message to the device. Like updating the display
once a minute.

There wasn’t anything obvious to prevent this sleep (nothing in the GATT).

If you just want a dial, check out the Teenage Engineering Ortho Remote. It
uses BLE Midi out of the box, so paint with a mac gives you volume control.
It’s also nicer designed, but there’s no project there :)

**Comment by thedriveman** [comment]
I've tested it and sending a periodic display update as a "keep alive" indeed keeps the controller from falling asleep. I'm going explore this option further, and also assess what is the battery drainage toll. Thanks a lot!

**Comment by DrCWO** [comment]
> I've tested it and sending a periodic display update as a "keep alive" indeed keeps the controller from falling asleep. I'm going explore this option further, and also assess what is the battery drainage toll. Thanks a lot!



> I'm building an app that listens to rotate events, and I've noticed that after about 5 minutes of inactivity (i.e., not touching the controller), rotate events stop getting dispatched . However, once I press the controller surface, a select event is getting dispatched, after which rotate events start dispatching again. It does look like the Bluetooth connection remains connected during the entire time, as no disconnected event is dispatched.
> 
> Does the controller hardware go to "light" sleep after 5 minutes, where only a select event wakes it up?

Did you really solve this issue? I Did output a character to the display every 10 seconds to keep it alive. No matter how long I wait, sometimes rotation events were created sometimes not. Seems to be random for me. 

Comments will be appreciated. Thanks
